SCI-7598 Switch to original Janino bundles, rather than the ServiceMix version
The Janino and Common-compiler OSGI bundles that we put first in the target
platform were the versions (re)published by Apache ServiceMix, since at that
time Janino was not available elsewhere as OSGI bundles (see DAQ-952).

Unfortunately, the ServiceMix OSGI-ified versions have a problem with the source
bundles, which produce error messages that look like this:
ERROR: Problem processing bundle manifest source header in plug-in Apache ServiceMix :: Bundles :: commons-compiler version 3.0.7_1
java.lang.IllegalArgumentException: invalid version "3.0.7_1": non-numeric "7_1"

Since we don't really need the source bundles for these, and since OSGI
bundles are now available from org.codehaus, switch to using those.

Change-Id: I19f4e476e81c4ba5ae480bc1ad7896b42badc497